---
global:
  image:
    repository: "ghcr.io/goauthentik/server"
    tag: "2025.6.3"
    pullPolicy: IfNotPresent
authentik:
  secret_key: ojUjEz2wv3O44cLvEdJSAbhJCo0NMDeg
  postgresql:
    host: postgres.local
    name: authentik
    user: authentik
    password: lyaPwh0qC87rIbzBv8aifnCzXqklblUt
    port: 5432
  error_reporting:
    enabled: false
  log_level: error
server:
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-issuer
    hosts:
      - authentik.example.com
    tls:
      - secretName: traefik-tls
        hosts:
          - authentik.example.com
postgresql:
  enabled: false
redis:
  enabled: true
