version: v2
teleport:
  nodename: your-server-name
  data_dir: /var/lib/teleport
  log:
    output: stderr
    severity: INFO
    format:
      output: text
  ca_pin: ""
  diag_addr: ""
auth_service:
  enabled: "yes"
  listen_addr: 0.0.0.0:3025
  proxy_listener_mode: multiplex
  cluster_name: your-server-url
  # ---
  # (Optional) Passwordless Authentication
  # authentication:
  #   type: local
  #   second_factor: on
  #   webauthn:
  #     rp_id: your-server-url
  #   connector_name: passwordless
  # ---
ssh_service:
  enabled: "yes"
  commands:
  - name: hostname
    command: [hostname]
    period: 1m0s
proxy_service:
  enabled: "yes"
  web_listen_addr: 0.0.0.0:443
  public_addr: your-server-url
  https_keypairs: []
  acme: {}
  # ---
  # (Optional) ACME
  # acme:
  #   enabled: "yes"
  #   email: your-email-address
  # ---

