image:
  repository: traefik
  version: v3.2.3
  pullPolicy: IfNotPresent

# --> (Optional) Change log settings here...
# logs:
#   general:
#     level: ERROR
#   access:
#     enabled: false
# <--

# --> (Optional) Redirect HTTP to HTTPs by default
# ports:
#   web:
#     redirectTo: 
#       port: websecure
# <--
