---
image:
  repository: quay.io/jetstack/cert-manager-controller
  tag: v1.16.3
webhook:
  image:
    repository: quay.io/jetstack/cert-manager-webhook
    tag: v1.16.3
cainjector:
  image:
    repository: quay.io/jetstack/cert-manager-cainjector
    tag: v1.17.0

crds:
  enabled: true

extraArgs:
  - --dns01-recursive-nameservers-only
  - --dns01-recursive-nameservers=1.1.1.1:53,1.0.0.1:53
