---
kind: kubernetes
schema: "1.0"
metadata:
  name: Kubernetes ConfigMap
  description: >
    Kubernetes ConfigMap resource for storing non-sensitive configuration data as key-value pairs.


    ConfigMaps allow you to decouple configuration from container images.


    Documentation: https://kubernetes.io/docs/concepts/configuration/configmap/
  version: 1.31.0
  author: Christian Lempa
  date: '2025-01-11'
spec:
  general:
    vars:
      resource_name:
        default: app-config
