apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ingressroutetcp
  # (Optional) Namespace
  # namespace: your-namespace
  # ---
spec:
  entryPoints:
  - web
  - websecure
  routes:
  - match: HostSNI(`your-hostname-sni`)
    priority: 10
    services:
    - name: your-service
      port: 80
  # (Optional) TLS Passthrough
  # tls:
  #   passthrough: true
  # ---