---
services:
  authentik_proxy:
    image: ghcr.io/goauthentik/proxy:2024.8.0
    container_name: authentik-outpost
    environment:
      - AUTHENTIK_HOST=${AUTHENTIK_HOST:?error}
      - AUTHENTIK_INSECURE=${AUTHENTIK_INSECURE:-false}
      - AUTHENTIK_TOKEN=${AUTHENTIK_TOKEN:?error}
    restart: unless-stopped
