apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress # Name of the ingress object
  namespace: namespace # Name of the namespace
spec:
  rules:
  - host: "your-hostname.com"  # Your hostname
    http:
      paths:
      # Path-based routing settings:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: your-service-name  # The name of the service
            port:
              number: 80  # Service Portnumber