---
image:
  longhorn:
    engine:
      repository: "longhornio/longhorn-engine"
      tag: "v1.8.0"
    manager:
      repository: "longhornio/longhorn-manager"
      tag: "v1.8.0"
    ui:
      repository: "longhornio/longhorn-ui"
      tag: "v1.8.0"
    instanceManager:
      repository: "longhornio/longhorn-instance-manager"
      tag: "v1.8.0"
    shareManager:
      repository: "longhornio/longhorn-share-manager"
      tag: "v1.8.0"
    backingImageManager:
      repository: "longhornio/backing-image-manager"
      tag: "v1.8.0"
    supportBundleKit:
      repository: "longhornio/support-bundle-kit"
      tag: "v0.0.49"
  csi:
    attacher:
      repository: "longhornio/csi-attacher"
      tag: "v4.8.0"
    provisioner:
      repository: "longhornio/csi-provisioner"
      tag: "v5.2.0"
    nodeDriverRegistrar:
      repository: "longhornio/csi-node-driver-registrar"
      tag: "v2.13.0"
    resizer:
      repository: "longhornio/csi-resizer"
      tag: "v1.13.1"
    snapshotter:
      repository: "longhornio/csi-snapshotter"
      tag: "v8.2.0"
    livenessProbe:
      repository: "longhornio/livenessprobe"
      tag: "v2.15.0"

# --> (Optional) Reduce the number of replicas of Longhorn UI
# longhornUI:
#   replicas: 1
# <--

# --> (Optional) Change the default settings, like Backup Target here...
# defaultSettings:
#   backupTarget: "your-backup-target"  # <-- Replace with your backup target
# <--
