---
- name: deploy portainer-ce latest
  hosts: "{{ hosts }}"
  become: yes
  become_user: "{{ lookup('env','USER') }}"
  tasks:
  - name: create new volume
    community.docker.docker_volume:
      name: portainer-data
  - name: deploy portainer
    community.docker.docker_container:
      name: portainer
      image: "docker.io/portainer/portainer-ce"
      ports:
        - "9443:9443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer-data:/data
      restart_policy: unless-stopped