---
kind: ansible
metadata:
  name: Manage Checkmk Hosts
  description: |-
    Ansible playbook to manage hosts in Checkmk monitoring. Create or update host configuration in Checkmk.

    Project: https://checkmk.com
    Documentation: https://docs.checkmk.com/
  version: 2.4.0
  author: Christian Lempa
  date: "2025-11-11"
  tags: []
  icon:
    provider: selfh
    id: checkmk
  draft: false
  next_steps: ""
schema: "1.0"
spec:
  checkmk:
    title: Checkmk Configuration
    required: true
    vars:
      checkmk_server_url:
        description: Checkmk server URL
        type: hostname
        default: checkmk.home.arpa
      checkmk_site:
        description: Checkmk site name
        type: str
        default: cmk
  general:
    vars:
      become:
        type: str
        default: false
      playbook_name:
        default: Manage Checkmk hosts
      target_hosts:
        type: str
        default: localhost
  host:
    title: Host Configuration
    required: true
    vars:
      host_folder:
        description: Folder path in Checkmk
        type: str
        default: /
      host_ip:
        description: IP address of the host
        type: str
        default: host-ip-address
      host_name:
        description: Hostname to add to Checkmk
        type: str
        default: your-host-name
  options:
    title: options
    vars:
      gather_facts:
        type: str
        default: false
      options_enabled:
        type: str
        default: true
  secrets:
    title: secrets
    vars:
      secrets_enabled:
        type: str
        default: true
