---
# -- (Optional) When using Traefik, use this section
# networks:
#   your-traefik-network:
#     external: true
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport-distroless:18.0.2
    container_name: teleport
    ports:
      # -- (Optional) Remove this section, when using Traefik
      - "3080:3080"
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
    volumes:
      - ./config:/etc/teleport
      - ./data:/var/lib/teleport
    # -- (Optional) Traefik example configuration
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.services.teleport.loadbalancer.server.port=3080"
    #   - "traefik.http.services.teleport.loadbalancer.server.scheme=https"
    #   - "traefik.http.routers.teleport-http.entrypoints=web"
    #   - "traefik.http.routers.teleport-http.rule=HostRegexp(`^(?i)(?:[[:alnum:]]+(?:-+[[:alnum:]]+)*\\.)?your-server-url(?::\\d+)?$`)"
    #   - "traefik.http.routers.teleport-https.entrypoints=websecure"
    #   - "traefik.http.routers.teleport-https.rule=HostRegexp(`^(?i)(?:[[:alnum:]]+(?:-+[[:alnum:]]+)*\\.)?your-server-url(?::\\d+)?$`)"
    #   - "traefik.http.routers.teleport-https.tls=true"
    #   - "traefik.http.routers.teleport-https.tls.certresolver=your-certresolver"
    #   - "traefik.http.routers.teleport-https.tls.domains[0].main=your-server-url"
    #   - "traefik.http.routers.teleport-https.tls.domains[0].sans=*.your-server-url"
    # networks:
    #   - your-traefik-network
    restart: unless-stopped
