---
# -- (Optional) When using a custom network
# networks:
#   your-custom-network:
#     -- (Optional) When attaching an external network
#     external: true
services:
  twingate_connector:
    container_name: twingate_connector
    image: docker.io/twingate/connector:1.72.0
    environment:
      - TWINGATE_NETWORK=your-twingate-network
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
      # -- (Optional) Change loglevel
      # - TWINGATE_LOG_LEVEL=3
      # -- (Optional) Add custom DNS Server
      # - TWINGATE_DNS=10.20.0.1
    sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
    # -- (Optional) When using a custom network
    # networks:
    #   - your-custom-network
    restart: unless-stopped
