---
volumes:
  mariadb-data:
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    # (Optional) Expose Container outside
    # ports:
    #   - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: your-root-password
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: unless-stopped