---
services:
  homer:
    image: docker.io/b4bz/homer:v23.10.1
    container_name: homer
    ports:
      - "8080:8080"
    volumes:
      - /etc/homer/assets/:/www/assets
    restart: unless-stopped
