---
kind: ansible
metadata:
  icon:
    provider: selfh
    id: ansible
  name: Add SSH Key and Configure Sudoers
  description: >
    Ansible playbook to add SSH public key to authorized_keys.
    Also configures passwordless sudo for sudo group.


    Project: https://www.openssh.com

    Documentation: https://www.openssh.com/manual.html
  version: 1.0.0
  author: Christian Lempa
  date: '2025-11-11'
  draft: true
schema: "1.2"
spec:
  general:
    vars:
      target_hosts:
        description: Target hosts
        type: str
        required: true
      playbook_name:
        default: Add ssh key
      become:
        default: true
